name: workflow_dispatch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get github
        run: |
          curl -vL \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/acn-devops-template/feat-test-package/pulls/41 \
          -d '{"title":"#AB7 Test","body":"updated body","state":"open","base":"main"}'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install pip and twine
        run: |
          pip install --upgrade pip
          pip install twine

      - name: Install poetry
        uses: ./inst-poetry
        with:
          version: 1.6.1

      - name: Install dependencies and project
        run: |
          poetry install -v --without interactive,docs

      - name: Build package
        run: |
          poetry build -f wheel
          
      - name: Publish package to Azure Artifact
        run: |
          poetry run twine upload dist/*
          echo "Building package"
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.AZURE_ARTIFACTS_PAT }}
          TWINE_REPOSITORY_URL: https://pkgs.dev.azure.com/kBank-MDF-SANDBOX/_packaging/kBank-MDF-SANDBOX/pypi/upload
